### ISSUE TITLE
Question about the STL files

### ISSUE THREAD

**Issue by george-andr** [Lite3DP/Lite3DP-Zero#1]
Where can one find the STLs to print the lite3dp-zero? The repo seems to be empty?

**Comment by Lite3DP** [comment]
@george-andr

Hi George, thanks for your interest. This repository is public but it is under preparation. In a few weeks all the documentation will be available. You can also contact us and try a beta version: lite3dp@lite3dp.com

**Comment by george-andr** [comment]
OK, thanks
